#!/usr/bin/env python3
import socket
import time


def wait_for(host: str, port: int) -> None:
    while True:
        try:
            with socket.create_connection((host, port), timeout=5):
                return
        except OSError:
            time.sleep(5)


print("Waiting for ClickHouse and Postgres to be ready", flush=True)
wait_for("clickhouse", 9000)
print("ClickHouse is ready", flush=True)
wait_for("db", 5432)
print("Postgres is ready", flush=True)
